# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syrinx.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Streamer.Band" do
    optional :uid, :string, 1
    optional :key, :string, 2
  end
  add_message "Streamer.TuneRequest" do
    optional :band, :message, 1, "Streamer.Band"
  end
  add_message "Streamer.Video" do
    optional :index, :string, 1
    optional :chunk, :bytes, 2
  end
  add_message "Streamer.BroadcastResponse" do
    optional :success, :bool, 1
    optional :band, :message, 2, "Streamer.Band"
  end
end

module Streamer
  Band = Google::Protobuf::DescriptorPool.generated_pool.lookup("Streamer.Band").msgclass
  TuneRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Streamer.TuneRequest").msgclass
  Video = Google::Protobuf::DescriptorPool.generated_pool.lookup("Streamer.Video").msgclass
  BroadcastResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("Streamer.BroadcastResponse").msgclass
end
